[tool.black]
line-length = 88

[tool.ruff]
line-length = 88
select = ["E", "F", "I"]

[tool.pytest.ini_options]
python_files = "test_*.py"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"